version: "3.8"

secrets:
  ssl_certificate:
    file: "/etc/letsencrypt/live/<DOMAIN>/fullchain.pem"
  ssl_certificate_key:
    file: "/etc/letsencrypt/live/<DOMAIN>/privkey.pem"

services:
  gophish:
    container_name: "gophish"
    image: "gophish/gophish"
    expose:
      - "3333"
      - "80"
    networks:
      - "phish_net"
    volumes:
      - "./gophish/config.json:/opt/gophish/config.json"
      - "./gophish/gophish.db:/opt/gophish/gophish.db"
      - "./gophish/gophish.log:/opt/gophish/gophish.log"
      - "./site/:/opt/gophish/static/endpoint/"
  nginx:
    container_name: "nginx"
    image: "nginx"
    ports:
      - "443:443"
      - "80:80"
      - "127.0.0.1:8080:8080"
    links:
      - "gophish"
    networks:
      - "phish_net"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/nginx.log:/var/log/nginx/access.log" 
    secrets:
      - "ssl_certificate"
      - "ssl_certificate_key"
    depends_on:
      - "gophish"

networks:
   phish_net:
    driver: "bridge"
    ipam:
     driver: "default"
     config:
       - subnet: "172.27.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: "phish_net" # use < 15 chars
